name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install

      - name: Run type checking
        run: pnpm run types
        continue-on-error: true

      - name: Run linting
        run: pnpm run lint
        continue-on-error: true

      - name: Run code formatting
        run: pnpm run format
